insert={mode='n', keys=['i']}
visual={mode='n', keys=['v']}
normal={mode='vi', keys=['esc']}

into_command_line={mode='nv', keys=[':']}
into_search={mode='nv', keys=['/']}

left={mode='*', keys=['left']}
right={mode='*', keys=['right']}
up={mode='*', keys=['up']}
down={mode='*', keys=['down']}

hover={mode='n', keys=['k']}
jump={mode='n', keys=['space', 'space']}
files={mode='n', keys=['space', 'f']}
lsp_stop={mode='n', keys=['l', 's']}
toggle_log={mode='n', keys=['l', 'l']}

print_key_map={mode = 'n', keys=['?']}
yank={mode = 'v', keys=['y']}
